### ISSUE TITLE
[Insight] Text files should end with a newline character - in bookservice/…/resources/application.yml, line 7

### ISSUE THREAD

**Issue by ravelmello** [CrabTech/projetounipe#13]
**[in bookservice/src/main/resources/application.yml, line 7](https://github.com/CrabTech/projetounipe/blob/478030ca82517de646bfb3336b4b3e03ade91203/bookservice/src/main/resources/application.yml#L7)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
    port: 8082
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
            
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/4c25ba4b-249f-462e-a8b8-d94347c8ad14/analyses/5)_
